version: '3'

services:
  db:
    image: postgres
    container_name: lil-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: hamzabelmellouki
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hamzabelmellouki
    networks:
      - product-net

  product:
    image: ensa/product-manager
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - product-net

networks:
  product-net:
    driver: bridge
volumes:
  db:
    driver: local
